version: 2

python:
  version: 3
  install:
      - requirements: docs/requirements.txt
      - method: pip
        path: .

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false