[build-system]
requires = ["chronver", "setuptools>=66"]
build-backend = "setuptools.build_meta"

[project]
authors = [{ name = "Chris Hall", email = "chall@radiasoft.net" }]
dependencies = [
  "libEnsemble",
  "ruamel.yaml",
  "jinja2",
  "numpy",
  "pydantic",
  "sortedcontainers",
  "typer",
  "lark",
  "pytest>=9.1.1",
]
description = "A Python library with tools for optimization problems"
dynamic = ["version"]
name = "rsopt"
readme = "README.md"

[project.scripts]
rsopt = "rsopt.rsopt_console:main"

[project.optional-dependencies]
full = [
  'rsbeams@git+https://github.com/radiasoft/rsbeams',
  'sirepo@git+https://github.com/radiasoft/sirepo',
  'DFO-LS',                                           # If using dfols optimizer
  'scipy',
  'nlopt',
  'pandas',                                           # Needed for some post-processing utilities
  'xopt',                                             # If using MOBO algorithm for optimization
  'pymoo',                                            # Used by some MOBO examples
  'deap',                                             # Used for NSGA-II algorithm implementation
]

[tool.setuptools.packages.find]
where = ["."]
include = ["rsopt*"]

[tool.setuptools.package-data]
"rsopt" = ["package_data/**"]

[tool.pyright]
venvPath = "."
venv = ".venv"

