codes:
  - python:
      parameters:
        x:
          min: -3.
          max: 3.
          start: 0.08
          samples: 5
        y:
          min: -2.
          max: 2.
          start: -0.7
          samples: 5
      setup:
        input_file: six_hump_camel.py
        function: six_hump_camel_func
        execution_type: serial
options:
  software: mesh_scan
  nworkers: 4
  run_dir: scan_data
  sim_dirs_make: False  #  Set to True if each simulation should be run in a new subdirectory under `run_dir`
