codes:
  - python:
      parameters:
        x:
          min: -3.
          max: 3.
          start: 0.08
        y:
          min: -2.
          max: 2.
          start: -0.7
      setup:
        input_file: six_hump_camel.py
        function: six_hump_camel_func_dfols
        execution_type: serial
options:
  nworkers: 4
  software: aposmm
  method: dfols
  record_interval: 25
  software_options:
    initial_sample_size: 50
    max_active_runs: 3
    local_opt_options:
      components: 3
  exit_criteria:
    sim_max: 400
