codes:
  - python:
      parameters:
        x:
          min: -3.
          max: 3.
          start: 0.08
        y:
          min: -2.
          max: 2.
          start: -0.7
      setup:
        input_file: six_hump_camel.py
        function: six_hump_camel_func
        execution_type: serial
options:
  nworkers: 4
  initial_sample_size: 50
  max_active_runs: 3
  software: aposmm
  method: nlopt.LN_BOBYQA
  record_interval: 25
  software_options: {'ftol_abs': 1.0e-4,
                     'dist_to_bound_multiple': 0.5}
  exit_criteria:
    sim_max: 400