%YAML 1.1
---
codes:
    - python:
        settings:
            a: 1.0
        parameters:
            x: 
                min: -2            
                max:  2            
                start: 1.2  
                samples: 50
            y:             
                min: -1            
                max:  3           
                start: 1.9 
                samples: 50
        setup:           
            input_file: func.py   
            function: rosenbrock_raise
            execution_type: serial
options:
    software: mesh_scan
    nworkers: 4
    run_dir: scan_rosenbrock
