codes:
  - python:
      setup:
        input_file: python_file.py
        function: main
        execution_type: serial
        force_executor: True
        cores: 1
  - user:
      setup:
        run_command: get_env
        execution_type: serial
        cores: 1
        environment_variables:
          MY_NEW_VAR: 4242
          ANOTHER_IS: "hi_there"
options:
  nworkers: 1
  software: mesh_scan